name: 'Jupyter to Markdown Action'
description: 'Converts Jupyter notebooks to markdown files, preserving frontmatter.'
author: 'Your Name'

inputs:
  github_token:
    description: 'GitHub token to allow the action to commit files.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'book-open'
  color: 'blue'
