name: 'Jupyter to Markdown Action'
description: 'Converts Jupyter notebooks to markdown files, preserving frontmatter.'
author: 'Tech Tana'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'book-open'
  color: 'blue'
