name: Test Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create test notebooks
        run: |
          mkdir -p _jupyter_notebook
          echo '{ "cells": [ { "cell_type": "raw", "metadata": {}, "source": [ "title: Test Post with Frontmatter\n", "author: Gemini" ] }, { "cell_type": "markdown", "metadata": {}, "source": [ "# This is a test notebook" ] }, { "cell_type": "code", "execution_count": null, "metadata": {}, "outputs": [], "source": [ "print(\"Hello, World!\")" ] } ], "metadata": {}, "nbformat": 4, "nbformat_minor": 4 }' > _jupyter_notebook/test_with_frontmatter.ipynb
          echo '{ "cells": [ { "cell_type": "markdown", "metadata": {}, "source": [ "# This is a test notebook without frontmatter" ] }, { "cell_type": "code", "execution_count": null, "metadata": {}, "outputs": [], "source": [ "print(\"Hello, again!\")" ] } ], "metadata": {}, "nbformat": 4, "nbformat_minor": 4 }' > _jupyter_notebook/test_without_frontmatter.ipynb

      - name: Run action
        uses: ./

      - name: Verify output
        run: |
          set -e
          ls -R
          test -f _posts/test_with_frontmatter.md
          test -f _posts/test_without_frontmatter.md
          test -f _posts/test_with_frontmatter.ipynb
          test -f _posts/test_without_frontmatter.ipynb
          grep -q "title: Test Post with Frontmatter" _posts/test_with_frontmatter.md
          grep -q "author: Gemini" _posts/test_with_frontmatter.md
          grep -q "# This is a test notebook" _posts/test_with_frontmatter.md
          grep -q "print(\"Hello, World!\")" _posts/test_with_frontmatter.md
          grep -q "# This is a test notebook without frontmatter" _posts/test_without_frontmatter.md
          grep -q "print(\"Hello, again!\")" _posts/test_without_frontmatter.md